### PR TITLE
fix for torch10

### PR DESCRIPTION
**Pull request by likholat**
- [ ] Needs to fix for `instance_norm=True`

### CODE REVIEW

**Comment by dkurt** [comment]
Disable instance norm tests

**Comment by likholat** [comment]
### Performance results

 Shape| Origin time (ms) | OpenVino time (ms)
:--: | :--: | :--:
[3, 3, 16, 16] | 5.31 |  1.49 **(x3.65)**
[2, 5, 16, 32] | 5.6 | 1.71 **(x3.27)**
[2, 5, 64, 128] | 13.4 |  12.28 **(x1,09)**

Measured on `Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz` with `PyTorch 1.10.0`.


A code similar to the `test_rim.py` was used for the measurement:
```
import torch
import time
import argparse

from direct.data.transforms import fft2, ifft2
from direct.nn.rim.rim import RIM
from direct.nn.openvino.openvino_model import OpenVINOModel
from tests.tests_nn.test_rim import create_input


def main():
    parser = argparse.ArgumentParser(description='Generate model and test data')
    parser.add_argument('--shape', type=int, nargs='+', default=[3, 3, 16, 16])
    args = parser.parse_args()

    shape = args.shape
    n = 30

    model = RIM(
        fft2,
        ifft2,
        hidden_channels=4,
        length=3,
        depth=2,
        no_parameter_sharing=True,
        instance_norm=False,
        dense_connect=True,
        skip_connections=True,
        image_initialization="input-kspace",
    ).cpu()

    img = create_input([shape[0]] + shape[2:] + [2]).cpu()
    kspace = create_input(shape + [2]).cpu()
    sens = create_input(shape + [2]).cpu()
    mask = create_input([shape[0]] + [1] + shape[2:] + [1]).round().int().cpu()

    out = model(img, kspace, mask, sens)

    start = time.time()
    for i in range(n):
        model(img, kspace, mask, sens)
    torch_time = (time.time() - start) / n

    ov_model = OpenVINOModel(model)
    ov_out = ov_model(img, kspace, mask, sens)

    start = time.time()
    for i in range(n):
        ov_model(img, kspace, mask, sens)
    ov_time = (time.time() - start) / n

    print("Torch time:", f"{torch_time * 1000:.{3}f}", "ms")
    print("OV time:", f"{ov_time * 1000:.{3}f}", "ms")


if __name__ == "__main__":
    main()
```

**Comment by dkurt** [comment]
> <html>
<body>


[2, 5, 64, 128] | 13.4 | 12.28 (x1,09)
-- | -- | --



</body>
</html>


Please provide per-layer type benchmarking for 64x128

**Review by dkurt — APPROVED** [review]

**Comment by likholat** [comment]
Layer | time
-- | --
Gather | 2841
Convolution | 2139
Reorder | 2065
Select | 1576
FFT | 1460
Equal | 507
ScatterNDUpdate | 488
ComplexMultiplication | 258
PowerStatic | 247
AvgPool | 238
Concat | 234
Multiply | 229
Transpose | 218
Pad | 122
Relu | 63

**Comment by dkurt** [comment]
Still too much Reorder and Gather ops. Let's continue localizing and removing them. Also Select seems suspicious.

**Pull request merged**
